#ifndef _MXWIDGETCODE_H_
#define _MXWIDGETCODE_H_

#define interface struct

enum ACTIONCODE { MX_QUIT, MX_CLOSE, MX_OPEN, MX_MINIMIZE, MX_MAXIMIZE, MX_KEYDOWN, MX_KEYUP, MX_MOUSEDOWN, MX_MOUSEUP, MX_MOUSEMOVE, MX_DIMFADE, MX_DIMSHOW, MX_HIDE, MX_SHOW,
	MX_RESIZE, MX_DROP, MX_COPY, MX_PASTE, MX_CUT, MX_BUTTON_CLICKED,  MX_EDIT_ENTER,  MX_NULL
};

enum { MSG_IGNORED, MSG_PROC, MSG_FOCUS, MSG_REMOVE, MSG_CLICKED, MSG_NULL };
enum WINDOW_STATE { MAX, MINI, NORMAL, MINIMIZING };

#endif

